# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Turing Tests
email: jgeddes@turing.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  A collection of data science challenges
baseurl: "/turing-tests" # the subpath of your site, e.g. /blog
url: "http://alan-turing-institute.github.io" # the base hostname & protocol for your site
github_username:  alan-turing-institute

# Build settings
markdown: kramdown
